"""command receipts for idempotency

Revision ID: 8a499dd3840a
Revises: b5c9c21107ff
Create Date: 2026-07-30 17:36:29.171709
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8a499dd3840a'
down_revision = 'b5c9c21107ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_receipts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'completed')", name='ck_receipt_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_command_receipts_created', [sa.literal_column('created_at DESC')], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_command_receipts_created')

    op.drop_table('command_receipts')
    # ### end Alembic commands ###
