"""baseline schema

Revision ID: b5c9c21107ff
Revises: 
Create Date: 2026-07-30 17:24:24.112962
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b5c9c21107ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('inputs', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_session_ts', ['session_id', sa.literal_column('timestamp DESC')], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'closed')", name='ck_chat_session_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_date', name='uq_chat_session_user_date')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_chat_sessions_user_date', ['user_id', sa.literal_column('session_date DESC')], unique=False)

    op.create_table('meals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('food_item', sa.Text(), nullable=False),
    sa.Column('quantity', sa.REAL(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('calories', sa.REAL(), nullable=False),
    sa.Column('protein_g', sa.REAL(), nullable=False),
    sa.Column('carbs_g', sa.REAL(), nullable=False),
    sa.Column('fat_g', sa.REAL(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('meal_type', sa.Text(), nullable=True),
    sa.Column('eaten_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index('ix_meals_user_eaten', ['user_id', sa.literal_column('eaten_at DESC')], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_goals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('calories', sa.REAL(), nullable=False),
    sa.Column('protein_g', sa.REAL(), nullable=False),
    sa.Column('carbs_g', sa.REAL(), nullable=False),
    sa.Column('fat_g', sa.REAL(), nullable=False),
    sa.Column('water_ml', sa.REAL(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_goals', schema=None) as batch_op:
        batch_op.create_index('ix_nutrition_goals_user_active', ['user_id', 'is_active'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed', 'overdue')", name='ck_tasks_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_user_status_due', ['user_id', 'status', 'due_date'], unique=False)

    op.create_table('water_intake',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('amount_ml', sa.REAL(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('exercise', sa.Text(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.REAL(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.REAL(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('worked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index('ix_workouts_user_date', ['user_id', sa.literal_column('worked_out_at DESC')], unique=False)

    # Added by hand: autogenerate cannot reflect expression-based indexes, so
    # it silently skips this one. Every PR/history lookup matches the exercise
    # case-insensitively and needs it.
    op.create_index(
        'ix_workouts_user_exercise',
        'workouts',
        ['user_id', sa.text('lower(exercise)')],
        unique=False,
    )

    op.create_table('chat_messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_chat_message_role'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_session_created', ['session_id', sa.literal_column('created_at DESC')], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_session_created')

    op.drop_table('chat_messages')
    op.drop_index('ix_workouts_user_exercise', table_name='workouts')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index('ix_workouts_user_date')

    op.drop_table('workouts')
    op.drop_table('water_intake')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_user_status_due')

    op.drop_table('tasks')
    with op.batch_alter_table('nutrition_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_nutrition_goals_user_active')

    op.drop_table('nutrition_goals')
    op.drop_table('notes')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index('ix_meals_user_eaten')

    op.drop_table('meals')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_sessions_user_date')

    op.drop_table('chat_sessions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_session_ts')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
